import Transition from "@/components/Transition"

export const metadata = {
    title: "About",
    description: "Generated by create next app",
  }

export default function Layout({children}) {
  return (
    <>
    <Transition/>
    <div>{children}</div>
    </>
  )
}
